### ISSUE TITLE
No migration or database in the files.

### ISSUE THREAD

**Issue by ZamfiAlex** [abertnamanya/Dental-Medical-Managment-System#2]
I was starting myself to to do a laravel dental medical management for my wife and just found this and tried to install it, but it seems the seeds or SQL file is missing from it.

**Comment by abertnamanya** [comment]
Hi @ZamfiAlex , Its good that your interested in this project. Let me try and push the migration files
Regards

**Comment by abertnamanya** [comment]
@ZamfiAlex please try to fork the Repository. The Issue has been resolved
